config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :news, expect: [:show, :new, :edit]
  resources :sections, expect: [:show, :new, :edit]
  root 'tasks#index'
  resources :priorities, expect: [:show, :new, :edit]
  resources :tasks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
  belongs_to :section

  validates :url, {presence: true}
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authenticate
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @all_news = News.all

    if params[:id].present?
      set_news
    else
      @news = News.new
    end
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    @news.user = current_user

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_url, notice: "#{@news.url}を作成しました。" }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to request.referer, notice: "#{@news.url}を更新しました。" }
        format.json { render :show, status: :ok, location: @news }
      else
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    url = @news.url
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "#{url}を削除しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:url, :delete_flg, :user_id, :section_id)
    end

    def authenticate
      redirect_to '/users/sign_in' unless user_signed_in?
    end

end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>News</h1>

  <%= form_for(@news) do |f| %>
      <div class="form-group">
        <% if @news.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

              <ul>
                <% @news.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :url %>
          <%= f.text_field :url, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :section %>
          <%= f.collection_select :section_id, Section.all, :id, :name, {prompt: true}, {class: 'form-control input-width200'} %>
        </div>

        <div class="actions">
          <%= f.submit('登録する', class: 'btn btn-primary') %>
        </div>
      </div>
  <% end %>


  <table class="table table-hover">
    <thead>
      <tr>
        <th>Url</th>
        <th>分類</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @all_news.each do |news| %>
        <tr>
          <td><%= news.url %></td>
          <td><%= news.section.name %></td>
          <td><%= link_to '編集', news_index_path(id: news.id), class: 'btn btn-primary' %></td>
          <td><%= link_to '削除', news, method: :delete, data: { confirm: '削除してもよろしいでしょうか?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to '新規登録', news_index_path, class: 'btn btn-primary' %>
</div>